# Generated by Django 3.1.7 on 2021-03-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buisnessname', models.CharField(max_length=100)),
                ('contactperson1', models.CharField(max_length=100)),
                ('contactdetails1', models.CharField(max_length=100)),
                ('contactemail1', models.CharField(max_length=100)),
                ('contactperson2', models.CharField(max_length=100)),
                ('contactdetails2', models.CharField(max_length=100)),
                ('contactemail2', models.CharField(max_length=100)),
                ('mailingaddress', models.CharField(max_length=100)),
                ('zipcode1', models.CharField(max_length=100)),
                ('billingaddress', models.CharField(max_length=100)),
                ('zipcode2', models.CharField(max_length=100))
            ],
        ),
        migrations.CreateModel(
            name='merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('placeorderid', models.IntegerField()),
                ('offerid', models.IntegerField()),
                ('typeofpackage', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('itemprice', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('merchantname', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('billingtype', models.CharField(max_length=100))

            ],
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('passcode', models.CharField(max_length=100)),
                ('billingtype', models.CharField(max_length=100)),
                ('materialtype', models.CharField(max_length=100)),
                ('addonstype', models.CharField(max_length=100)),
                ('addonsnumber', models.CharField(max_length=100))
            ],
        ),

    ]
